Setup tox and finalize frontend
philippschmalen/Green-charge pull request #3
Opened 2022-12-10 14:09 UTC by jhubaum

This MR sets up a basic testing workflow using tox and adds a github action to execute the testing pipeline whenever a branch is pushed to a pull request. It also fixes the visualization of the charging windows in the frontend. I will do refactoring of how the time data is stored in the database in a follow-up PR.

## Pre-merge checklist
- [ ] Successfully deploy server and test the visualization of charging windows
  - This currently doesn't work since, for some reason, the celery worker is unable to connect to the database

2022-12-10 14:27 UTC, jhubaum commented
@philippschmalen Can you change the protection settings of `main` so that we're only able to merge an MR when all checks have passed?

2022-12-10 20:36 UTC, philippschmalen commented
Unfortunately, I cannot select the `Run Python CI` yet as a status check. I guess we first have to merge everything before I can specify it.

![image](https://user-images.githubusercontent.com/9386378/206874314-b09346ee-af2f-4fd3-873c-796be090eaa5.png)

2022-12-10 20:50 UTC, philippschmalen commented on tests/test_config.py
> +import yaml
Was confused first if you meant to create `conftest.py` like https://stackoverflow.com/questions/34466027/in-pytest-what-is-the-use-of-conftest-py-files , but it's used for fixtures.
Then I found test_config.py in the pytest repo https://github.com/pytest-dev/pytest/blob/main/testing/test_config.py . So, now I get it :)

2022-12-10 21:06 UTC, philippschmalen requested changes
Nice work! Just some details to discuss.

2022-12-10 21:06 UTC, philippschmalen commented on src/data/redis_pandas_handler.py
> +    df = df.copy()
Avoid weird issues with `df = df.copy()` , different naming instead: `df_cp = df.copy()`

2022-12-10 21:06 UTC, philippschmalen commented on src/data/redis_pandas_handler.py
> +                "+" if end_time is None else datetime_to_timestamp(end_time),
Nice!

2022-12-11 10:16 UTC, jhubaum commented on src/backend/api.py
> +        return f"ts::device::{self.device.id}::{name}"
I agree, and want to refactor most of the current redis interaction. I renamed the device keys in 4f11fd9 and would refactor the interaction in a follow-up PR. Or do you want me to do this before merging?

2022-12-11 10:19 UTC, jhubaum commented on tests/test_config.py
> +import yaml
So, nothing to do here, right? Or do you want to me to rename the test file?

2022-12-11 12:16 UTC, jhubaum commented on src/data/redis_pandas_handler.py
> +    df = df.copy()
What weird issues? FWIW, `datetimeindex_to_unix` does the same thing and I want to refactor the redis handling in a way where both of these functions will become obsolete anyway. Unless you strongly object, I will ignore this for this MR.

2022-12-11 12:17 UTC, jhubaum commented
From my side this is ready to merge. @philippschmalen Do you have any other objections?

2022-12-11 12:38 UTC, philippschmalen approved these changes

2022-12-11 12:56 UTC, philippschmalen commented
> Before, we only stored the charging state in Redis. This is enough to
> control devices using MQTT. To visualize the charging windows, however,
> we also need the predicted value from the optimizer.

Instead of writing "a wrapper function to split a dataframe into multiple timeseries" we could query Redis twice for `ts:preprocessed` (values used for prediction) and `ts:charge`. So, we have the choice between 
1. Query Redis 2x on ts:charge, ts:preprocessed and merge on timestamp
2. write a wrapper that splits a dataframe

I prefer (1) as it introduces a dynamic mapping btw. a dataframe and Redis. Better to keep it deterministic to be more transparent & robust.
In addition to that, we need to refactor `src.data.visualize_intervals:plot_charging_windows` in a way that it handles unix timestamps within the dataframe and converts those to human-readable ones in user timezone.  Plotly handles the overlay of the two timeseries automatically, when they have the same length, throwing exception otherwise.

2022-12-11 13:07 UTC, jhubaum commented
> Instead of writing "a wrapper function to split a dataframe into multiple timeseries" we could query Redis twice for ts:preprocessed (values used for prediction) and ts:charge.

Good point, I hadn't considered that. I agree, (1) is the better option. Since this MR was supposed to be only about fixing the frontend, I will implement this in my follow-up refactoring MR. I want to merge this now, so that we have a first running version available on `main` before I start breaking things again :D

I'll look into refactoring `plot_charging_windows` there as well.

2022-12-11 13:13 UTC, merged